### ISSUE TITLE
Summarized number of points are not showing up anymore in Board view for each column

### ISSUE THREAD

**Issue by andreasbossard** [vkorobov-boostlabs/asana-counter#4]
The extension seems not to do anymore what it should be doing.
Summarized number of points are not showing up anymore in Board view.
<img width="328" alt="point-summarizing not working" src="https://user-images.githubusercontent.com/502464/70158095-f0523600-16b6-11ea-9d88-bd62761f79f0.png">

**Comment by matheusouzaaaa** [comment]
Truth. Stopped working for me both in board and list view

**Comment by matheusouzaaaa** [comment]
This may help you

> Uncaught TypeError: Cannot read property 'insertBefore' of undefined at script.js:131

**Comment by matheusouzaaaa** [comment]
Hi! 

Maybe this can help

boardHeaderRow = document.getElementsByClassName("Board-header")[0]; have to change to boardHeaderRow = document.getElementsByClassName("BoardColumn-header")[0];

**Comment by matheusouzaaaa** [comment]
And have to change the correct selector for the LIST mode too.

**Comment by matheusouzaaaa** [comment]
hello, @terpimost ? Can you fix it?

**Comment by andreasbossard** [comment]
@matheusouzaaaa I will create a fix and PR. I just hope that @terpimost will react, because there is another PR waiting since August...

**Comment by matheusouzaaaa** [comment]
> @matheusouzaaaa I will create a fix and PR. I just hope that @terpimost will react, because there is another PR waiting since August...

Nice! Nice work, my friend! Hey @terpimost , PR the @andreasbossard fix. Thank you!

**Comment by mmueller-cm** [comment]
Seconded! @terpimost Please PR this.

**Comment by terpimost** [comment]
Hey, guys, I'm so sorry that I didn't get notification from GitHub and didn't see your comments. I accepted your pull requests and republished the fix. If you want to co-own publishing let me know. We can do it via Google Group
@andreasbossard @matheusouzaaaa @mmueller-cm

**Comment by mmueller-cm** [comment]
No worries at all! Thanks for publishing the fix; it works like a charm!

**Comment by andreasbossard** [comment]
@terpimost thank you for publishing! I would be happy to co-own publishing. DM me on twitter https://twitter.com/AndreasBossard
